name: faiss-hs
version: 0.0.1.0
github: "tusharad/faiss-hs"
license: MIT
author: "tushar"
maintainer: "tusharadhatrao@gmail.com"
copyright: "2025 tushar"

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis: Haskell bindings for faiss
category: similarity, clustering, bindings

description: Please see the README on GitHub at <https://github.com/tusharad/faiss-hs#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  extra-lib-dirs:
    - /usr/local/lib
  extra-libraries:
    - faiss_c

tests:
  faiss-hs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - faiss-hs
      - tasty
      - tasty-hunit
      - random
      - vector
