snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/23/26.yaml
packages:
  - .
extra-deps:
  - ../
  - langchain-hs-0.0.2.0@sha256:744646dc3f3db847ff160b30d7ffa04249d49a72910c364072b953c6b5376562,4464

