name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: freckle/stack-action/generate-matrix@v5
    outputs:
      stack-yamls: ${{ steps.generate.outputs.stack-yamls }}

  build:
    needs: generate
    strategy:
      matrix:
        stack-yaml: ${{ fromJSON(needs.generate.outputs.stack-yamls) }}
      fail-fast: false

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Copy repo into actions
        uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "stack build --stack-yaml ${{ matrix.stack_yaml }}"
      
  tests:
    needs: build

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Copy repo into actions
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "stack test"
